/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { PlayerCoordinator } from "./lib/player-coordinator";
import { PlayerOptions } from "./lib/types";
export namespace Components {
    interface AudioControls {
        "playerCoordinator": PlayerCoordinator;
    }
    interface AudioCore {
        "play": () => Promise<void>;
        "playerCoordinator": PlayerCoordinator;
        "stop": () => Promise<void>;
    }
    interface RbupAudio {
        "chromeless": boolean;
        "play": () => Promise<void>;
        "setup": (options: PlayerOptions) => Promise<void>;
        "src": string;
        "stop": () => Promise<void>;
    }
}
declare global {
    interface HTMLAudioControlsElement extends Components.AudioControls, HTMLStencilElement {
    }
    var HTMLAudioControlsElement: {
        prototype: HTMLAudioControlsElement;
        new (): HTMLAudioControlsElement;
    };
    interface HTMLAudioCoreElement extends Components.AudioCore, HTMLStencilElement {
    }
    var HTMLAudioCoreElement: {
        prototype: HTMLAudioCoreElement;
        new (): HTMLAudioCoreElement;
    };
    interface HTMLRbupAudioElement extends Components.RbupAudio, HTMLStencilElement {
    }
    var HTMLRbupAudioElement: {
        prototype: HTMLRbupAudioElement;
        new (): HTMLRbupAudioElement;
    };
    interface HTMLElementTagNameMap {
        "audio-controls": HTMLAudioControlsElement;
        "audio-core": HTMLAudioCoreElement;
        "rbup-audio": HTMLRbupAudioElement;
    }
}
declare namespace LocalJSX {
    interface AudioControls {
        "playerCoordinator"?: PlayerCoordinator;
    }
    interface AudioCore {
        "playerCoordinator"?: PlayerCoordinator;
    }
    interface RbupAudio {
        "chromeless"?: boolean;
        "src"?: string;
    }
    interface IntrinsicElements {
        "audio-controls": AudioControls;
        "audio-core": AudioCore;
        "rbup-audio": RbupAudio;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "audio-controls": LocalJSX.AudioControls & JSXBase.HTMLAttributes<HTMLAudioControlsElement>;
            "audio-core": LocalJSX.AudioCore & JSXBase.HTMLAttributes<HTMLAudioCoreElement>;
            "rbup-audio": LocalJSX.RbupAudio & JSXBase.HTMLAttributes<HTMLRbupAudioElement>;
        }
    }
}
